version: '3.8'

services:
  postgresgame1:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: master
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data2

  postgresmaster:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data2

  masterapi:
    build:
      context: .
      dockerfile: MasterApi/Dockerfile
    ports:
      - "44364:44364"
    depends_on:
      - postgresmaster
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44364
      - ConnectionStrings__MasterCatalog=Host=postgresmaster;Port=5432;Database=master;Username=postgres;Password=password
  game1:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "44356:44356"
    depends_on:
      - postgresgame1
      - masterapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44356
      - ConnectionStrings__GameCatalog=Host=postgresgame1;Port=5433;Database=master;Username=postgres;Password=password

volumes:
  postgres_data:
