// <auto-generated />
using System;
using MasterApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MasterApi.Data.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20260531113929_AddDiscordAccountLink")]
    partial class AddDiscordAccountLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MasterApi.Data.Entities.BuildingLayoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAccountId", "BuildingType");

                    b.ToTable("BuildingLayoutTemplates");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GameNewsEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TargetServerKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TargetServerKey", "PublishedAtUtc");

                    b.ToTable("GameNewsEntries");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GameNewsEntryLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameNewsEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.HasKey("Id");

                    b.HasIndex("GameNewsEntryId", "Locale")
                        .IsUnique();

                    b.ToTable("GameNewsEntryLocalizations");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GameNewsReadReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameNewsEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServerKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("GameNewsEntryId", "PlayerEmail", "ServerKey")
                        .IsUnique();

                    b.ToTable("GameNewsReadReceipts");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GameServerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackendUrl")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<int>("CompanyCount")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentTick")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrontendUrl")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("GraphqlUrl")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServerKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ServerKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ServerKey")
                        .IsUnique();

                    b.HasIndex("ServerKeyHash")
                        .IsUnique();

                    b.ToTable("GameServers");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GlobalGameAdminGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("GlobalGameAdminGrants");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GoldTokenDepositRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("DepositAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenderAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAccountId", "RequestedAtUtc");

                    b.HasIndex("Status", "RequestedAtUtc");

                    b.ToTable("GoldTokenDepositRequests");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GoldTokenTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("PlayerAccountId");

                    b.ToTable("GoldTokenTransactions");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GoldTokenWithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAccountId", "RequestedAtUtc");

                    b.HasIndex("Status", "RequestedAtUtc");

                    b.ToTable("GoldTokenWithdrawalRequests");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterPlayerSession", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSeenIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("PlayerAccountId", "LastSeenAtUtc");

                    b.ToTable("MasterPlayerSessions");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingBountyAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BountyDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ChangedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValueJson")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("PreviousValueJson")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.HasKey("Id");

                    b.HasIndex("BountyDefinitionId", "CreatedAtUtc");

                    b.ToTable("MasterRankingBountyAudits");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingBountyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CooldownMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleToPlayers")
                        .HasColumnType("boolean");

                    b.Property<string>("ProofRequirement")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("RequiresModeration")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RewardPoints")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SourceEventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationSettingsJson")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("VisibilityScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MasterRankingBountyDefinitions");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingEvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ProcessedEvents")
                        .HasColumnType("integer");

                    b.Property<int>("RewardRecordsCreated")
                        .HasColumnType("integer");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("TotalPointsAfterDecay")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalPointsAwarded")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalPointsBeforeDecay")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("RunType", "StartedAtUtc");

                    b.ToTable("MasterRankingEvaluationRuns");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModeratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeratedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ModerationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<Guid?>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProofReference")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<string>("QuarantineClearJustification")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("QuarantineClearedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuarantineClearedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QuarantineReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("QuarantinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuarantinedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ServerKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ServerKeyHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("TelemetryBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelemetryNonce")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("TelemetrySignatureHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UniqueScopeKey")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalEventId")
                        .IsUnique();

                    b.HasIndex("PlayerAccountId");

                    b.HasIndex("ProofReference")
                        .IsUnique();

                    b.HasIndex("EventType", "Status", "CreatedAtUtc");

                    b.HasIndex("PlayerEmail", "EventType", "ServerKey", "IdempotencyKey");

                    b.ToTable("MasterRankingEvents");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingPlayerSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GlobalRank")
                        .HasColumnType("integer");

                    b.Property<decimal>("LastDailyDecayFactorApplied")
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("PreviousGlobalRank")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPoints")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GlobalRank");

                    b.HasIndex("PlayerAccountId")
                        .IsUnique();

                    b.ToTable("MasterRankingPlayerSnapshots");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingRewardRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AwardMetadataJson")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateTime>("AwardedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BountyDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EventDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PointsAwarded")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("RankingEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServerKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("UniquenessKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.HasKey("Id");

                    b.HasIndex("BountyDefinitionId");

                    b.HasIndex("RankingEventId");

                    b.HasIndex("UniquenessKey")
                        .IsUnique();

                    b.HasIndex("PlayerAccountId", "AwardedAtUtc");

                    b.ToTable("MasterRankingRewardRecords");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRevokedToken", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("PlayerAccountId", "RevokedAtUtc");

                    b.ToTable("MasterRevokedTokens");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("PlayerAccountId", "ExpiresAtUtc");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.PlayerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletionRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletionScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordLinkCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("DiscordLinkCodeExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DiscordUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EmailUnsubscribeToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("GoldTokenBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,8)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("HasReceivedRegistrationEmail")
                        .HasColumnType("boolean");

                    b.Property<string>("LastAccessedUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastWeeklyEmailSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PreferredLocale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en");

                    b.Property<DateTime?>("PreferredLocaleUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferredByEmail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegistrationEmailSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SessionRevokedBeforeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartupPackClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WeeklyReportEmailUnsubscribed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmailUnsubscribeToken")
                        .IsUnique();

                    b.ToTable("PlayerAccounts");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.ProSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAccountId");

                    b.ToTable("ProSubscriptions");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.RankingTelemetryAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClearJustification")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventNonce")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("boolean");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PlayerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QuarantineReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("QuarantineUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuarantineUpdatedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ServerKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ServerKeyMasked")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ReasonCode");

                    b.HasIndex("BatchId", "CreatedAtUtc");

                    b.ToTable("RankingTelemetryAuditLogs");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.RankingTelemetryEventSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("SignatureHash")
                        .IsUnique();

                    b.ToTable("RankingTelemetryEventSignatures");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ContainsUnsafeContent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CreatedByPlayerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExtractedImagesJson")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("ExtractedUrlsJson")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("MarkdownSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModeratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeratedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ModerationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ModerationState")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("SanitizedPreviewHtml")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("StatusUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByPlayerAccountId", "CreatedAtUtc");

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.HasIndex("TicketType", "CreatedAtUtc");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.SupportTicketAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SupportTicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SupportTicketId", "CreatedAtUtc");

                    b.ToTable("SupportTicketAuditEvents");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.BuildingLayoutTemplate", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "PlayerAccount")
                        .WithMany()
                        .HasForeignKey("PlayerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerAccount");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GameNewsEntryLocalization", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.GameNewsEntry", "GameNewsEntry")
                        .WithMany("Localizations")
                        .HasForeignKey("GameNewsEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameNewsEntry");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GameNewsReadReceipt", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.GameNewsEntry", "GameNewsEntry")
                        .WithMany("ReadReceipts")
                        .HasForeignKey("GameNewsEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameNewsEntry");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GoldTokenDepositRequest", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "PlayerAccount")
                        .WithMany("GoldTokenDepositRequests")
                        .HasForeignKey("PlayerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerAccount");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GoldTokenTransaction", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "PlayerAccount")
                        .WithMany("GoldTokenTransactions")
                        .HasForeignKey("PlayerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerAccount");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GoldTokenWithdrawalRequest", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "PlayerAccount")
                        .WithMany("GoldTokenWithdrawalRequests")
                        .HasForeignKey("PlayerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerAccount");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterPlayerSession", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "PlayerAccount")
                        .WithMany("Sessions")
                        .HasForeignKey("PlayerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerAccount");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingBountyAudit", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.MasterRankingBountyDefinition", "BountyDefinition")
                        .WithMany("AuditTrail")
                        .HasForeignKey("BountyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BountyDefinition");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingEvent", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "PlayerAccount")
                        .WithMany("RankingEvents")
                        .HasForeignKey("PlayerAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlayerAccount");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingPlayerSnapshot", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "PlayerAccount")
                        .WithMany()
                        .HasForeignKey("PlayerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerAccount");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingRewardRecord", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.MasterRankingBountyDefinition", "BountyDefinition")
                        .WithMany("RewardRecords")
                        .HasForeignKey("BountyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "PlayerAccount")
                        .WithMany("RankingRewardRecords")
                        .HasForeignKey("PlayerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterApi.Data.Entities.MasterRankingEvent", "RankingEvent")
                        .WithMany("RewardRecords")
                        .HasForeignKey("RankingEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BountyDefinition");

                    b.Navigation("PlayerAccount");

                    b.Navigation("RankingEvent");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "PlayerAccount")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("PlayerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerAccount");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.ProSubscription", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "PlayerAccount")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlayerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerAccount");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.SupportTicket", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.PlayerAccount", "CreatedByPlayerAccount")
                        .WithMany()
                        .HasForeignKey("CreatedByPlayerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByPlayerAccount");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.SupportTicketAuditEvent", b =>
                {
                    b.HasOne("MasterApi.Data.Entities.SupportTicket", "SupportTicket")
                        .WithMany("AuditEvents")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.GameNewsEntry", b =>
                {
                    b.Navigation("Localizations");

                    b.Navigation("ReadReceipts");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingBountyDefinition", b =>
                {
                    b.Navigation("AuditTrail");

                    b.Navigation("RewardRecords");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.MasterRankingEvent", b =>
                {
                    b.Navigation("RewardRecords");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.PlayerAccount", b =>
                {
                    b.Navigation("GoldTokenDepositRequests");

                    b.Navigation("GoldTokenTransactions");

                    b.Navigation("GoldTokenWithdrawalRequests");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RankingEvents");

                    b.Navigation("RankingRewardRecords");

                    b.Navigation("Sessions");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MasterApi.Data.Entities.SupportTicket", b =>
                {
                    b.Navigation("AuditEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
