using System.ComponentModel.DataAnnotations;

namespace Api.Data.Entities;

/// <summary>
/// A unique referral code generated by a player and shareable with new users.
/// </summary>
public sealed class ReferralCode
{
    public Guid Id { get; set; }

    [Required, MaxLength(20)]
    public string Code { get; set; } = string.Empty;

    public Guid CreatorPlayerId { get; set; }

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

    public int UsageCount { get; set; }

    public Player CreatorPlayer { get; set; } = null!;

    public ICollection<ReferralRegistration> Registrations { get; set; } = new List<ReferralRegistration>();
}
